server:
  port: 12345

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/kopring
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true

infcon:
  location: coex
  date: 2023-08-15
  url: https://inflearn.com/conf/infcon-2023
